source 'https://rubygems.org'

gem 'active_model_serializers'
gem 'clearance'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'pg'
gem 'protected_attributes'
gem 'rails', '4.0.0'
gem 'sass-rails', '~> 4.0.0'
gem 'stripe', :git => 'https://github.com/stripe/stripe-ruby'
gem 'uglifier', '>= 1.3.0'
